version: '3'

services:
  dev_server:
    container_name: dev-green
    image: han990401/rgback-dev
    ports:
      - "18001:3000"
    env_file:
      - ../env/server.env
    networks:
      - rgback_dev
    volumes:
      - ../logs:/app/logs

# 이걸 필수로 넣어야 한다
networks:
  rgback_dev:
    driver: bridge
    external: true
    internal: true